version: '3'

services:
  sut:
    image: bleeper:dev
    build: .
    environment:
      NODE_ENV: test
      MONGODB_URI: mongodb://mongo/Bleeper-test
      jwtSecret: debug
      encKey: 00000000000000000000000000000000
    ports:
      - 8443:8443
    depends_on:
      - mongo
    command: npm test
  mongo:
    image: mongo:latest
